[server]
headless = false  # This ensures the browser opens
port = 8502  # Changed from 8501 to avoid port conflicts
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
serverPort = 8502  # Match the server port
gatherUsageStats = false
